'use client';

import LeftPanel from '@/components/LeftPanel';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import { initializeTheme } from '@/utils/darkLightMode';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    initializeTheme();
  }, []);

  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <LeftPanel />
        <Header />
        <main className="ml-72">{children}</main>
      </body>
    </html>
  );
}
